services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  bonus:
    build:
      context: .
      dockerfile: app/bonus/Dockerfile
    environment:
      - DB_HOST=postgres
      - POSTGRES_USER=program
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=privileges
      - HOST=bonus
      - PORT=8050
    ports:
      - "8050:8050"
    depends_on:
      - postgres

  flights:
    build:
      context: .
      dockerfile: app/flights/Dockerfile
    environment:
      - DB_HOST=postgres
      - POSTGRES_USER=program
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=flights
      - HOST=flights
      - PORT=8060
    ports:
      - "8060:8060"
    depends_on:
      - postgres

  tickets:
    build:
      context: .
      dockerfile: app/tickets/Dockerfile
    environment:
      - DB_HOST=postgres
      - POSTGRES_USER=program
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=tickets
      - HOST=tickets
      - PORT=8070
    depends_on:
      - postgres
    ports:
      - "8070:8070"

  gateway:
    build:
      context: .
      dockerfile: app/gateway/Dockerfile
    environment:
      - FLIGHTS_SERVICE_URL=http://flights:8060
      - TICKETS_SERVICE_URL=http://tickets:8070
      - PRIVILEGES_SERVICE_URL=http://bonus:8050
      - AUTH_CLIENT_ID=ds
      - AUTH_CLIENT_SECRET=DSrFTJQIogtflWlTcS9mtoZVia5IoNes
      - IDP_ENDPOINT=http://127.0.0.1/realms/ds/protocol/openid-connect/token
      - JWKS_ENDPOINT=http://127.0.0.1/realms/ds/protocol/openid-connect/certs
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - flights
      - tickets
      - bonus

volumes:
  db-data:
